### PR TITLE
fix: broken scripts

### LINKED ISSUE #4: Broken Scripts
**Describe the bug**
`Install-BuildKit` attempts to untar files into directory with the name of the tarball itself.
`Install-ContainerTools` is unable to find `downloadfile` macro.

**To Reproduce**
1. `Import-Module -Name "./ContainerToolsForWindows" -Force`
2. `Install-Buildkit`
3. `Install-ContainerTools`

**Expected behavior**
Installation to be successful.

**Screenshots**
kegIgcE04Q

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 23H2

**Additional context**

### PR DESCRIPTION
**Pull request by fruzitent**
fixes #4 

d4pFFilgNP

`Install-ContainerTools` should call `Install-*`?

### CODE REVIEW

**Review by TinaMor — DISMISSED** [review]
Thank you for the fix.

**Review by profnandaa — APPROVED** [review]

**Review by profnandaa — CHANGES_REQUESTED** [review]
Can fix the merge conflict?

**Review by bobsira — APPROVED** [review]

**Comment by fruzitent** [comment]
LudgSCRYqI

all 93 tests are passing as well

**Review by TinaMor — COMMENTED** [review]
> Install-ContainerTools should call Install-*?

The `Install-ContainerTools` command does the most basic: (1) Uninstall the tools (2) Download the files (3) "Install" the tool.

This should be a quick setup. For more control, the user should use the `Install-*` commands. For example, if they want to register and start the containerd, they can't do that with `Install-ContainerTools`. They'll have to use `Install-Cointaierd`

**Review by TinaMor — APPROVED** [review]

**Comment by TinaMor** [comment]
Please squash commits

**Review by iankingori — APPROVED** [review]

**Comment by iankingori** [comment]
> > Install-ContainerTools should call Install-*?
> 
> The `Install-ContainerTools` command does the most basic: (1) Uninstall the tools (2) Download the files (3) "Install" the tool.
> 
> This should be a quick setup. For more control, the user should use the `Install-*` commands. For example, if they want to register and start the containerd, they can't do that with `Install-ContainerTools`. They'll have to use `Install-Containerd`

@TinaMor does this mean `Install-ContainerTools` will not register the service? Can we add a switch to provide a Register-Service option

**Review by profnandaa — APPROVED** [review]

**Pull request merged**
